//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Controle.java
//  @ Date : 03/11/2018
//  @ Author : 
//
//




public class Controle {
	public Object setbtnCima;
	public Object setbtnDireita;
	public Object setbtnBaixo;
	public Object setbtnEsquerda;
}
